version: "3.9"
services:
  web:
    build:
      context: ./
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www
    depends_on:
      - mongodb
    env_file:
      - .env

  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"